import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./ui/globals.scss";
import Navbar from "./ui/layout/navbar";
import Footer from "./ui/layout/footer";
import Provider from "@/util/Providers";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.className} antialiased`}>
        <Navbar />
        <Provider>{children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
