import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./ui/globals.scss";
import Navbar from "./ui/layout/navbar";
import Footer from "./ui/layout/footer";
import Provider from "@/util/Providers";
import { CartProvider } from "../util/CartProvider";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.className} antialiased`}>
        <CartProvider>
          <Navbar />
          <Provider>{children}</Provider>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
